"""Define package versions."""

FOSS_NIRS_6500_VERSION = "0.2.0"
THERMOFISHER_NANODROP_VERSION = "0.2.0"

SPECTROPHOTOMETRY_PATH = "zontal/applications/spectrophotometry"
FOSS_NIRS_6500_IMAGE = f"{SPECTROPHOTOMETRY_PATH}/zontal-foss-nirs-6500:{FOSS_NIRS_6500_VERSION}"
THERMOFISHER_NANODROP_IMAGE = f"{SPECTROPHOTOMETRY_PATH}/zontal-thermofisher-nanodrop:{THERMOFISHER_NANODROP_VERSION}"
